package gitops

import (
	"fmt"

	"github.com/yourorg/github-code-agent/features/fixer"
	"github.com/yourorg/github-code-agent/pkg/constants"
)

// MessageGenerator handles generation of commit and PR messages
type MessageGenerator struct{}

// NewMessageGenerator creates a new MessageGenerator instance
func NewMessageGenerator() *MessageGenerator {
	return &MessageGenerator{}
}

// GenerateCommitMessage generates a commit message for fixes
func (m *MessageGenerator) GenerateCommitMessage(patches []*fixer.CodePatch) string {
	if len(patches) == 0 {
		return fmt.Sprintf("%s Automated fixes", constants.GitCommitEmoji)
	}

	if len(patches) == 1 {
		return fmt.Sprintf("%s Auto-fix: %s", constants.GitCommitEmoji, patches[0].Description)
	}

	return fmt.Sprintf("%s Auto-fix: %d issues resolved", constants.GitCommitEmoji, len(patches))
}

// GeneratePRTitle generates a PR title for fix PR
func (m *MessageGenerator) GeneratePRTitle(prNumber int, fixCount int) string {
	return fmt.Sprintf("%s Automated fixes for PR #%d (%d issues)", constants.GitCommitEmoji, prNumber, fixCount)
}

// GeneratePRBody generates a PR description for fix PR
func (m *MessageGenerator) GeneratePRBody(prNumber int, patches []*fixer.CodePatch) string {
	body := fmt.Sprintf(`## Automated Code Review Fixes

This PR contains automated fixes for issues found in PR #%d.

### Issues Fixed:

`, prNumber)

	for i, patch := range patches {
		body += fmt.Sprintf("%d. **%s** in `%s` (line %d)\n", i+1, patch.Description, patch.FilePath, patch.Line)
	}

	body += `
### Validation Results:

All fixes have been validated for:
- ✅ Syntax correctness
- ✅ Linting compliance
- ✅ Code formatting
- ✅ Security checks

Please review and merge if changes are acceptable.

---
🤖 Generated by [GitHub Code Agent](https://github.com/yourorg/github-code-agent)
`

	return body
}

// GenerateFixDescription generates a human-readable description of a single fix
func (m *MessageGenerator) GenerateFixDescription(patch *fixer.CodePatch) string {
	return fmt.Sprintf("Fixed issue in %s at line %d: %s",
		patch.FilePath, patch.Line, patch.Description)
}
